use crate::{alignment::AncestralAlignment, bail, tkf_model::blocks_of_alignment, Result};

#[derive(Clone, Debug)]
pub struct Fragmentation {
    right_fragment_boundaries: Vec<usize>,
}

impl Fragmentation {
    pub(super) fn new(fragments: Vec<usize>) -> Result<Self> {
        Self::is_increasing(&fragments)?;
        Ok(Fragmentation {
            right_fragment_boundaries: fragments,
        })
    }

    fn is_increasing(fragments: &[usize]) -> Result<()> {
        // if fragments.is_empty() {
        //     bail!(Tkf, "fragmentation is empty")
        // } else if fragments.last().unwrap() == &0 {
        //     bail!(Tkf, "fragmentation last element is 0")
        if !fragments.windows(2).all(|w| w[0] < w[1]) {
            bail!(
                Tkf,
                "fragmentation is not strictly increasing, got {fragments:?}"
            )
        }
        Ok(())
    }

    pub fn right_exclusive_boundaries(&self) -> &[usize] {
        &self.right_fragment_boundaries
    }

    /// Returns the number of fragments.
    pub fn len(&self) -> usize {
        self.right_fragment_boundaries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.right_fragment_boundaries.is_empty()
    }

    pub(super) fn fragmentation_works_with_ancestral_alignment<AA: AncestralAlignment>(
        &self,
        masa: &AA,
    ) -> Result<()> {
        if self.is_empty() {
            if masa.len() == 0 {
                return Ok(());
            } else {
                bail!(Tkf, "fragmentation and alignment do not match in emptiness")
            }
        }
        // - get the blocks of the alignment, these indices must also be in the fragmentation
        if self.right_exclusive_boundaries().last().unwrap() != &masa.len() {
            bail!(Tkf, "fragmentation does not match alignment length")
        }

        let blocks = blocks_of_alignment(masa);
        for block in blocks {
            if !self.right_fragment_boundaries.contains(&block) {
                bail!(Tkf, "fragmentation does not contain block border {block}")
            }
        }
        Ok(())
    }

    /// When [remove_extinct_columns](`crate::alignment::AncestralAlignment::remove_extinct_columns`) is
    /// called on a simulated alignment generated by either
    /// [TKFMSASimulator::simulate](`crate::tkf_model::simulate_msa::TKFMSASimulator::simulate_with_fragments`) or
    /// [TKFIndelMSASimulator::simulate](`crate::tkf_model::simulate_msa::TKFIndelMSASimulator::simulate_with_fragments`),
    /// the corresponding fragmentation goes out of sync with the alignment. This function removes the
    /// columns that were removed from the alignment from the fragmentation, so that it is in sync
    /// again.
    pub(super) fn remove_cols(&mut self, keep_col_mask: &[bool]) -> Result<()> {
        if self.is_empty() {
            if keep_col_mask.is_empty() {
                return Ok(());
            } else {
                bail!(Tkf, "fragmentation and alignment do not match in emptiness")
            }
        }
        let mut new_fragmentation = Vec::with_capacity(self.len());

        let mut prev_border = 0;
        let mut removed_so_far = 0;
        if self.right_exclusive_boundaries().last().unwrap() != &keep_col_mask.len() {
            bail!(Tkf, "fragmentation does not match alignment length")
        }
        for frag_border in self.right_fragment_boundaries.iter() {
            let mask_slice = &keep_col_mask[prev_border..*frag_border];
            if mask_slice.iter().all(|&b| !b) {
                removed_so_far += mask_slice.len();
                // not keep ie remove
            } else if mask_slice.iter().all(|&b| b) {
                // keep
                new_fragmentation.push(*frag_border - removed_so_far);
            } else {
                bail!(Tkf, "mask does not match fragmentation")
            }
            prev_border = *frag_border;
        }
        Self::is_increasing(&new_fragmentation)?;
        self.right_fragment_boundaries = new_fragmentation;
        Ok(())
    }
}

#[cfg(test)]
#[cfg_attr(coverage, coverage(off))]
mod private_tests {

    use super::*;
    use crate::Error::Tkf;
    use assert_matches::assert_matches;
    use rstest::*;

    #[rstest]
    #[case(vec![])]
    #[case(vec![0])]
    #[case(vec![3, 3, 5])]
    fn fragmentation_init_valid(#[case] frag: Vec<usize>) {
        let fragmentation = Fragmentation::new(frag.clone()).unwrap();
        assert_eq!(fragmentation.right_exclusive_boundaries(), &frag);
    }

    #[rstest]
    #[case(vec![3, 2, 5])]
    #[case(vec![3, 3, 5])]
    fn fragmentation_init_invalid(#[case] frag: Vec<usize>) {
        let err = Fragmentation::new(frag.clone());
        assert_matches!(err.unwrap_err(), Tkf(msg) if msg.contains("fragmentation is not strictly increasing"));
    }

    #[test]
    fn remove_cols_from_fragmentation_no_removals() {
        let mut fragmentation = Fragmentation::new(vec![3, 6, 9]).unwrap();
        let keep_cols_mask = vec![true; 9];
        fragmentation.remove_cols(&keep_cols_mask).unwrap();
        assert_eq!(fragmentation.right_exclusive_boundaries(), vec![3, 6, 9]);
    }

    #[test]
    fn remove_cols_from_fragmentation_all_removals() {
        let mut fragmentation = Fragmentation::new(vec![3, 6, 9]).unwrap();
        let keep_cols_mask = vec![false; 9];
        let err = fragmentation.remove_cols(&keep_cols_mask);
        assert_matches!(err.unwrap_err(), Tkf(msg) if msg.contains("keep_col_mask is all false"));
    }

    #[test]
    fn remove_cols_from_fragmentation_first_removed() {
        let mut fragmentation = Fragmentation::new(vec![3, 7, 12]).unwrap();
        let keep_cols_mask = vec![
            false, false, false, true, true, true, true, true, true, true, true, true,
        ];
        fragmentation.remove_cols(&keep_cols_mask).unwrap();
        assert_eq!(fragmentation.right_exclusive_boundaries(), vec![4, 9]);
    }

    #[test]
    fn remove_cols_from_fragmentation_middle_removed() {
        let mut fragmentation = Fragmentation::new(vec![3, 7, 12]).unwrap();
        let keep_cols_mask = vec![
            true, true, true, false, false, false, false, true, true, true, true, true,
        ];
        fragmentation.remove_cols(&keep_cols_mask).unwrap();
        assert_eq!(fragmentation.right_exclusive_boundaries(), vec![3, 8]);
    }

    #[test]
    fn remove_cols_from_fragmentation_last_removed() {
        let mut fragmentation = Fragmentation::new(vec![3, 7, 12]).unwrap();
        let keep_cols_mask = vec![
            true, true, true, true, true, true, true, false, false, false, false, false,
        ];
        fragmentation.remove_cols(&keep_cols_mask).unwrap();
        assert_eq!(fragmentation.right_exclusive_boundaries(), vec![3, 7]);
    }

    #[test]
    fn remove_cols_from_fragmentation_larger_example() {
        let mut fragmentation = Fragmentation::new(vec![1, 3, 6, 10, 15, 21]).unwrap();
        let keep_cols_mask = vec![
            false, false, false, true, true, true, false, false, false, false, false, false, false,
            false, false, true, true, true, true, true, true,
        ];
        fragmentation.remove_cols(&keep_cols_mask).unwrap();
        assert_eq!(fragmentation.right_exclusive_boundaries(), vec![3, 9]);
    }

    #[test]
    fn remove_cols_from_fragmentation_empty_fragmentation() {
        let mut fragmentation = Fragmentation::new(vec![]).unwrap();
        let keep_cols_mask = vec![true, true, true];
        let err = fragmentation.remove_cols(&keep_cols_mask);
        assert_matches!(err.unwrap_err(), Tkf(msg) if msg.contains("fragmentation is empty"));
    }

    #[test]
    fn remove_cols_from_fragmentation_mismatched_lens() {
        let mut fragmentation = Fragmentation::new(vec![3, 6, 9]).unwrap();
        let keep_cols_mask = vec![true, true, true, true, true, true, true, true]; // length 8 instead of 9
        let err = fragmentation.remove_cols(&keep_cols_mask);
        assert_matches!(err.unwrap_err(), Tkf(msg) if msg.contains("fragmentation does not match alignment length"));
    }

    #[rstest]
    #[case(vec![true, false, true, true, true, true, true, true, true])]
    #[case(vec![false, false, true, true, true, true, true, false, true])]
    fn remove_cols_from_fragmentation_mask_does_not_match(#[case] keep_cols_mask: Vec<bool>) {
        let mut fragmentation = Fragmentation::new(vec![3, 6, 9]).unwrap();
        let err = fragmentation.remove_cols(&keep_cols_mask);
        assert_matches!(err.unwrap_err(), Tkf(msg) if msg.contains("mask does not match fragmentation"));
    }
}
