name: tests with coverage

on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-llvm-cov llvm-tools-preview
      - run: cargo llvm-cov --all-features --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
