name: tests with coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-llvm-cov
      - run: cargo llvm-cov --features ci_coverage --manifest-path phylo/Cargo.toml --all-features --workspace --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
